version: '3.7'

services:
  db:
    image: mysql:5.7.39
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - '3306:3306'
    command: --max_allowed_packet=1024M
    environment:
       MYSQL_USER: 'redg'
       MYSQL_PASSWORD: 'mmir2022'
       MYSQL_DATABASE: 'mmirdb'
       MYSQL_ROOT_PASSWORD: 'mmir2022'

  web:
    build: .
    expose:
      - 5000
    volumes:
      - static_volume:/opt/app/staticfiles
      - media_volume:/opt/app/media
    depends_on:
      - db
    env_file:
      - ./.env.dev
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/opt/app/staticfiles
      - media_volume:/opt/app/media
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:


