version: '3.7'

services:
  db:
    image: mysql:5.7.39
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - '3306:3306'
    command: --max_allowed_packet=1024M
    environment:
       MYSQL_USER: 'redg'
       MYSQL_PASSWORD: 'mmir2022'
       MYSQL_DATABASE: 'mmirdb'
       MYSQL_ROOT_PASSWORD: 'mmir2022'      
  web:
    build: .
    ports:
      - "8000:5000"
    depends_on:
      - db
    environment:
       DB_USER: 'redg'
       DB_PASS: 'mmir2022'
       DB_NAME: 'mmirdb'
       DB_HOST: 'db'
       DB_PORT: '3306'
       SERVICE_URL: '127.0.0.1'
       DEBUG: 'true'


